version: '3.9'

services:
  todo_db:
    image: postgres:14.2
    environment:
      POSTGRES_DB: todo_dev
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata
      PGTZ: Asia/Tomsk
      TZ: Asia/Tomsk
    volumes:
      - ./todo-db/initdb-scripts:/docker-entrypoint-initdb.d
      - ./todo-db/container-data:/var/lib/postgresql/data
    ports: 
      - 5439:5432
    restart: unless-stopped
